#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VillaKathrine.Resource", IsApplication=true)]

namespace VillaKathrine
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_devicedefault_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bedrooms = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int courtyard = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dining_room = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int parlor = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sitting_room = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int villa_main = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07002b
			public const int bedroom_button = 2131165227;
			
			// aapt resource value: 0x7f070028
			public const int courtyard_button = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int dining_button = 2131165225;
			
			// aapt resource value: 0x7f07000a
			public const int gridLayout1 = 2131165194;
			
			// aapt resource value: 0x7f070003
			public const int home_button = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int imageView1 = 2131165192;
			
			// aapt resource value: 0x7f070013
			public const int imageView10 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int imageView11 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int imageView12 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int imageView13 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int imageView14 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int imageView15 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int imageView16 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int imageView17 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int imageView18 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int imageView19 = 2131165212;
			
			// aapt resource value: 0x7f07000b
			public const int imageView2 = 2131165195;
			
			// aapt resource value: 0x7f07001d
			public const int imageView20 = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int imageView21 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int imageView22 = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int imageView23 = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int imageView24 = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int imageView25 = 2131165218;
			
			// aapt resource value: 0x7f07000c
			public const int imageView3 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int imageView4 = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int imageView5 = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int imageView6 = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int imageView7 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int imageView8 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int imageView9 = 2131165202;
			
			// aapt resource value: 0x7f070024
			public const int imageview = 2131165220;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout2 = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout3 = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int menu_toolbar = 2131165186;
			
			// aapt resource value: 0x7f070027
			public const int parlor_button = 2131165223;
			
			// aapt resource value: 0x7f070004
			public const int photos_button = 2131165188;
			
			// aapt resource value: 0x7f070023
			public const int return_button = 2131165219;
			
			// aapt resource value: 0x7f070026
			public const int room_desc = 2131165222;
			
			// aapt resource value: 0x7f070025
			public const int room_name = 2131165221;
			
			// aapt resource value: 0x7f070005
			public const int rooms_button = 2131165189;
			
			// aapt resource value: 0x7f07002a
			public const int sitting_button = 2131165226;
			
			// aapt resource value: 0x7f070009
			public const int textView1 = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int timeline_button = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int photos = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int room_info = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int rooms = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int timeline = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000a
			public const int ApplicationName = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int Contact = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int Home = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Photos = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Rooms = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int Timeline = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public const int Timeline_info = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int bedrooms = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int courtyard = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int dining_room = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int parlor = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int sitting_room = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
