#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VillaKathrine.Resource", IsApplication=true)]

namespace VillaKathrine
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bedrooms = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int courtyard = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dining_room = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int parlor = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sitting_room = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int villa_main = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05002b
			public const int bedroom_button = 2131034155;
			
			// aapt resource value: 0x7f050028
			public const int courtyard_button = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int dining_button = 2131034153;
			
			// aapt resource value: 0x7f05000a
			public const int gridLayout1 = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int home_button = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int imageView1 = 2131034120;
			
			// aapt resource value: 0x7f050013
			public const int imageView10 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int imageView11 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int imageView12 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int imageView13 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int imageView14 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int imageView15 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int imageView16 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int imageView17 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int imageView18 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int imageView19 = 2131034140;
			
			// aapt resource value: 0x7f05000b
			public const int imageView2 = 2131034123;
			
			// aapt resource value: 0x7f05001d
			public const int imageView20 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int imageView21 = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int imageView22 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int imageView23 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int imageView24 = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int imageView25 = 2131034146;
			
			// aapt resource value: 0x7f05000c
			public const int imageView3 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int imageView4 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int imageView5 = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int imageView6 = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int imageView7 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int imageView8 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int imageView9 = 2131034130;
			
			// aapt resource value: 0x7f050024
			public const int imageview = 2131034148;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout2 = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout3 = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int menu_toolbar = 2131034114;
			
			// aapt resource value: 0x7f050027
			public const int parlor_button = 2131034151;
			
			// aapt resource value: 0x7f050004
			public const int photos_button = 2131034116;
			
			// aapt resource value: 0x7f050023
			public const int return_button = 2131034147;
			
			// aapt resource value: 0x7f050026
			public const int room_desc = 2131034150;
			
			// aapt resource value: 0x7f050025
			public const int room_name = 2131034149;
			
			// aapt resource value: 0x7f050005
			public const int rooms_button = 2131034117;
			
			// aapt resource value: 0x7f05002a
			public const int sitting_button = 2131034154;
			
			// aapt resource value: 0x7f050009
			public const int textView1 = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int timeline_button = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int photos = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int room_info = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int rooms = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int timeline = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000a
			public const int ApplicationName = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int Contact = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int Home = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Photos = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Rooms = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int Timeline = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int VR = 2130968579;
            //does this need changed to timeline???


			
			// aapt resource value: 0x7f040008
			public const int bedrooms = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int courtyard = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int dining_room = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int parlor = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int sitting_room = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
